name: Deploy ICS to Supabase

on:
  push:
    branches:
      - main # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload .ics to Supabase
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        # Set variables
        FILE_PATH="WesternRite/LiturgicalCalendarWesterRite.ics" # Adjust to your .ics file location
        BUCKET_NAME="LiturigcalCalendars"
        FILE_NAME="LiturgicalCalendarWesterRite.ics"

        # Upload the file to Supabase
        curl -X POST "${SUPABASE_URL}/storage/v1/object/${BUCKET_NAME}/${FILE_NAME}" \
          -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
          -H "Content-Type: text/calendar" \
          --data-binary @"$FILE_PATH"

    - name: Generate Signed URL (Optional)
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        # Generate a signed URL (Optional Step)
        BUCKET_NAME="LiturigcalCalendars"
        FILE_NAME="LiturgicalCalendarWesterRite.ics"

        RESPONSE=$(curl -s -X POST "${SUPABASE_URL}/storage/v1/object/sign/${BUCKET_NAME}/${FILE_NAME}" \
          -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
          -H "Content-Type: application/json" \
          -d '{"expiresIn": 604800}') # Signed URL valid for 7 days (604800 seconds)

        echo "Signed URL: $RESPONSE"
