name: Deploy to Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set environment variables based on the branch
      - name: Set Environment Variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "BUCKET_NAME=LiturgicalCalendarsMain" >> $GITHUB_ENV
          fi
          echo "FILE_PATH=WesternRite/LiturgicalCalendarWesterRite.ics" >> $GITHUB_ENV
          echo "FILE_NAME=LiturgicalCalendarWesterRite.ics" >> $GITHUB_ENV

            # Debugging: Print environment variables
      - name: Debug - Print Variables
        run: |
          echo "Bucket Name: $BUCKET_NAME"
          echo "File Path: $FILE_PATH"
          echo "File Name: $FILE_NAME"
          echo "Supabase URL: $SUPABASE_URL"

      # Upload the file to Supabase bucket
      - name: Upload to Supabase
        run: |
          curl -X POST "${SUPABASE_URL}/storage/v1/object/${BUCKET_NAME}/${FILE_NAME}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: text/calendar" \
            --data-binary @"$FILE_PATH"

      # Debugging: Generate a signed URL to verify upload
      - name: Generate Signed URL
        run: |
          RESPONSE=$(curl -s -X POST "${SUPABASE_URL}/storage/v1/object/sign/${BUCKET_NAME}/${FILE_NAME}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"expiresIn": 604800}')
          echo "Signed URL: $RESPONSE"
